### ISSUE TITLE
ModuleNotFoundError when making example 1

### ISSUE THREAD

**Issue by dcam0050** [Pyrlang/Pyrlang#41] opened 2018-10-02 10:22 UTC
Hi there,

I'm using tag 0.9 on the master branch and after installing requirements with `pip install -r requirements.txt` I try running make example1 but I get the following error:

```
PYTHONPATH=/home/icub/user_files/project/bgvenv/Pyrlang:/home/icub/user_files/project/bgvenv/Pyrlang/Term PYRLANG_ENABLE_LOG_FORMAT=1 PYRLANG_LOG_LEVEL=DEBUG python3 examples/e01_simple_node.py
Traceback (most recent call last):
  File "examples/e01_simple_node.py", line 14, in <module>
    from pyrlang import Node
  File "/home/icub/user_files/project/bgvenv/Pyrlang/pyrlang/__init__.py", line 15, in <module>
    from pyrlang.node import Node, NodeException
  File "/home/icub/user_files/project/bgvenv/Pyrlang/pyrlang/node.py", line 20, in <module>
    from pyrlang.dist.distribution import ErlangDistribution
ModuleNotFoundError: No module named 'pyrlang.dist'
Makefile:12: recipe for target 'example1' failed
make: *** [example1] Error 1
```

I've also tried running other examples but I get the same error.

**Comment by kvakvs** [comment] 2018-10-02 11:35
Hello
Pyrlang examples use `pyrlang` library and `term` library (located on Github.com/pyrlang/term)
You need to either install both first, before running examples, or provide PYTHONPATH env variable with paths to these two projects, if you don't want to install.
Like this:
`PYTHONPATH=/home/icub/user_files/project/bgvenv/Pyrlang:/home/icub/user_files/project/bgvenv/Term make example1`

**Comment by kvakvs** [comment] 2018-10-02 13:17
Look in the Makefile for Pyrlang, and what Python it is using, it should use Python from your venv, and also your venv should be activated. The problem is clearly either a search path problem or using wrong Python.

**Comment by kvakvs** [comment] 2018-10-11 07:56
I assume that the problem is gone now, and closing this. Thanks for flying Pyrlang Airlines.

**Closed by kvakvs** 2018-10-11 07:56 UTC

**Comment by dcam0050** [comment] 2018-10-16 08:01
Sorry I've been away for a while and am now back on this problem. I've created a clean ubuntu docker container, installed python3.6, requirements for Term and installed Term using install rather than develop. Then I installed requirements of Pyrlang and performed an install.

After that I launch a python3 terminal and execute `import pyrlang` to which I still get the same error.

```
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrlang
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/icub/Pyrlang/pyrlang/__init__.py", line 15, in <module>
    from pyrlang.node import Node, NodeException
  File "/home/icub/Pyrlang/pyrlang/node.py", line 20, in <module>
    from pyrlang.dist.distribution import ErlangDistribution
ModuleNotFoundError: No module named 'pyrlang.dist'
```

I checked `/home/icub/Pyrlang/pyrlang` and there is no dist folder or file. I only have the following

```
__init__.py  __pycache__  async  bases.py  gen.py  gen_server.py  net_kernel.py  node.py  notebook  process.py  rex.py  util.py
```

Which explains why it cannot be found. So my question is, where is the file that is supposed to be imported?

**Comment by kvakvs** [comment] 2018-10-16 08:33
Found the problem.
Automatically generated .gitignore file for Python included "dist/" pattern which made dist folder disappear. I'm fixing this now.

**Comment by kvakvs** [comment] 2018-10-16 08:36
There is native version of the ETF library available written in Rust, it is though tricky to make file search paths work after you compiled it, I will look at paths later. It falls back to Python slower implementation and prints a warning.

**Comment by dcam0050** [comment] 2018-10-16 08:54
Thanks for the quick fix! Where can I find information on making it work with the ETF library?

**Comment by kvakvs** [comment] 2018-10-16 11:17
It is just the matter of Python finding .so library which I haven't fully figured out yet. There is nothing to fix because it works, if you provide Rust compiler and install the `etf` library with it, and then `make test` in ETF (term) library will run identical tests on native and Python implementations.

You can safely continue with Python implementation too, they are identical with Rust impl.

**Comment by dcam0050** [comment] 2018-10-22 21:02
Great thanks!
